[manager]
prepend_keymap = [
  # Hopping
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
	# Navigation
	{ on = "j", run = "leave", desc = "Go back to the parent directory" },
	{ on = "l", run = "enter", desc = "Enter the child directory" },

	{ on = "J", run = "back",    desc = "Go back to the previous directory" },
	{ on = "L", run = "forward", desc = "Go forward to the next directory" },
  # Seeking
	{ on = "I", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "K", run = "seek 5",  desc = "Seek down 5 units in the preview" },
]

[tasks]
prepend_keymap = [
  { on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
]

[spot]
prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
	{ on = "j", run = "swipe -1", desc = "Swipe to the next file" },
	{ on = "l", run = "swipe 1",  desc = "Swipe to the previous file" },
]

[pick]
prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
]

[input]
prepend_keymap = [
	# Mode
	{ on = "h", run = "insert",                              desc = "Enter insert mode" },
	{ on = "H", run = [ "move -999", "insert" ],             desc = "Move to the BOL, and enter insert mode" },
	# Character-wise movement
	{ on = "j",       run = "move -1", desc = "Move back a character" },
	{ on = "l",       run = "move 1",  desc = "Move forward a character" },
]

[confirm]
prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
]

[completion]
prepend_keymap = [
	{ on = "<A-i>", run = "arrow -1", desc = "Move cursor up" },
	{ on = "<A-k>", run = "arrow 1",  desc = "Move cursor down" },
]

[help]
prepend_keymap = [
	# Navigation
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
]
